inherited FormMod12: TFormMod12
  Caption = 'FormMod12'
  PixelsPerInch = 96
  TextHeight = 13
  inherited PageControl: TPageControl
    ActivePage = TabSheetModelDiagram
    inherited TabSheetGlobal: TTabSheet
      ExplicitLeft = 7
      ExplicitTop = 7
      ExplicitWidth = 931
      ExplicitHeight = 532
      inherited BitBtnMergeWeatherFN: TBitBtn
        Left = 1173
        Top = 920
        ExplicitLeft = 1173
        ExplicitTop = 920
      end
    end
    inherited TabSheetModelDiagram: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
      object Mod1: TMod
        Left = 299
        Top = 184
        Width = 94
        Height = 49
        Cursor = crHandPoint
        Parent = TabSheetModelDiagram
        TimeStep = 1.000000000000000000
        StartTime = 36161.000000000000000000
        EndTime = 36525.000000000000000000
        ModTime.Name = 'Time'
        ModTime.Opt_writetoFile = True
        ModTime.Opt_SelForSensOut = False
        ModTime.Opt_PlotToGraph = False
        ModTime.Opt_WriteFinalValue = False
        ModTime.Digits = 2
        ModTime.Precision = 6
        ModTime.v = 36161.000000000000000000
        LMOptions.IniLambda = 0.001000000000000000
        LMOptions.Divisor = 100.000000000000000000
        LMOptions.WeightOptions = OptNoWeight
        LMOptions.DefaultError = 0.100000000000000000
        LMOptions.OptOption = optOnlyActIni
        SensOpt.MaxValue = 10.000000000000000000
        SensOpt.MinValue = 1.000000000000000000
        SensOpt.Steps = 5
        SensOpt.DPar = 1.000000000000000000
        SensOpt.Sens_fn = 'sens.dat'
        ContOutput = True
        FinalOutput = False
        Str_SectionName_TimeInit = 'TimeInit'
        Str_SectionName_FileNames = 'FileNames'
        Str_SectionName_MeasurementFiles = 'MeasurementFiles'
        Str_SectionName_UpdateFiles = 'UpdateFiles'
        Str_SectionName_OutPutFiles = 'OutPutFiles'
        Str_SectionTopic_SimStart = 'Startzeit'
        Str_SectionTopic_SimEnd = 'Endzeit'
        Str_SectionTopic_TimeStep = 'TimeStep'
        Str_SectionTopic_StateIniFN = 'StateIniFN'
        Str_SectionTopic_ParamIniFN = 'ParamIniFN'
        Str_SectionTopic_WeatherFileFN = 'WeatherFileFN'
        Str_SectionTopic_OptionIniFN = 'OptionsIniFN'
        Str_SectionTopic_OutputDir = 'OutPutDir'
        ReInitAfterRun = True
        ShowDateFormat = True
      end
      object LogistGrowth1: TLogistGrowth
        Left = 107
        Top = 280
        Width = 174
        Height = 57
        Cursor = crHandPoint
        Parent = TabSheetModelDiagram
        SM_GlobMod = Mod1
        CompIndex = 0
        FN_ratefn = 'LogistGrowth1_rat.csv'
        FN_Statefn = 'LogistGrowth1_dat.csv'
        DebugModus = False
        St_Educt.Name = 'Educt'
        St_Educt.Comment = 'Educt'
        St_Educt.Opt_writetoFile = True
        St_Educt.Opt_SelForSensOut = False
        St_Educt.Opt_PlotToGraph = False
        St_Educt.Opt_WriteFinalValue = False
        St_Educt.Digits = 2
        St_Educt.Precision = 6
        St_Educt.v = 100.000000000000000000
        St_Product.Name = 'Product'
        St_Product.Opt_writetoFile = True
        St_Product.Opt_SelForSensOut = False
        St_Product.Opt_PlotToGraph = False
        St_Product.Opt_WriteFinalValue = False
        St_Product.Digits = 2
        St_Product.Precision = 6
        St_Product.v = 0.100000000000000000
        Par_gr.Name = 'gr'
        Par_gr.Comment = 'Growth rate parameter'
        Par_gr.Opt_writetoFile = False
        Par_gr.Opt_SelForSensOut = False
        Par_gr.Opt_PlotToGraph = False
        Par_gr.Opt_WriteFinalValue = False
        Par_gr.Digits = 2
        Par_gr.Precision = 6
        Par_gr.v = 0.020000000000000000
        Par_gr.opt_SelForSens = False
        Par_gr.max = 2.000000000000000000
        Par_S0.Name = 'S0'
        Par_S0.Comment = 'Initial amount of Substrate'
        Par_S0.Opt_writetoFile = False
        Par_S0.Opt_SelForSensOut = False
        Par_S0.Opt_PlotToGraph = False
        Par_S0.Opt_WriteFinalValue = False
        Par_S0.Digits = 2
        Par_S0.Precision = 6
        Par_S0.v = 100.000000000000000000
        Par_S0.opt_SelForSens = False
        Par_S0.max = 10000.000000000000000000
        Var_rgr.Name = 'rgr'
        Var_rgr.Opt_writetoFile = True
        Var_rgr.Opt_SelForSensOut = False
        Var_rgr.Opt_PlotToGraph = False
        Var_rgr.Opt_WriteFinalValue = False
        Var_rgr.Digits = 2
        Var_rgr.Precision = 6
        Ex_Temp.Name = 'Temp'
        Ex_Temp.Opt_writetoFile = True
        Ex_Temp.Opt_SelForSensOut = False
        Ex_Temp.Opt_PlotToGraph = False
        Ex_Temp.Opt_WriteFinalValue = False
        Ex_Temp.Digits = 0
        Ex_Temp.Precision = 0
        Ex_Temp.Ex = StateField
        Ex_Temp.Search = True
        Ex_Temp.C_f = 1.000000000000000000
      end
    end
    inherited TabSheetState: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetVariables: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetExternalValues: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetOptions: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetStat: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetResultTab: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetGraphResult: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
    inherited TabSheetDocumentation: TTabSheet
      ExplicitLeft = 4
      ExplicitTop = 4
      ExplicitWidth = 937
      ExplicitHeight = 538
    end
  end
end
