project:
  type: website
  execute-dir: project
  output-dir: docs


author: "Agronomy and Crop Science Group, Kiel University"
title: "Hume Documentation"

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Sub-models/components"
        contents:
          - Components/Evapotranspiration/Documentation/TPenMonteith.qmd
          - Components/Maize/Documentation/TMaizeDevelopment.qmd
      - section: "Technical PasDoc Documentation"
        contents:
          - file: PasDoc/UState/index.html
            text: "UState"
          - file: PasDoc/UMod/index.html
            text: "UMod"



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

page-footer:
  right: "Built with [Quarto](https://quarto.org/)"
  left: "&copy; Copyright 2025, Agronomy Group CAU Kiel"

toc: true
toc-expand: 4
toc-depth: 4
toc-location: left
bibliography: bibliography.bibtex.bib
csl: european-journal-of-agronomy.csl



