---
title: "Class description of TSoilWaterMod"
author: "Agronomy and Crop Science Group, Kiel University"
date: "`r Sys.Date()`"
chunk_output_type: console
html-math-method: katex
number-sections: true
toc: true
toc-expand: 4
toc-depth: 4
toc-location: left
crossref:
  eq-prefix: Eq.
format: 
  html:
    embed-resources: true 
---

```{r}
#| label: SetupLibraries
#| include: FALSE

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center", fig.width = 12, fig.height = 6, fig.pos = "h", fig.cap = TRUE)
rm(list = ls(all.names = TRUE))

library(rmarkdown)
library(bookdown)
library(soilwater)
library(pracma)
library(dplyr)
library(ggplot2)
library(extrafont)
library(gifski)
library(gganimate)
library(transformr)
library(reticulate)
library(tinytex)
library(magick)
library(bibtex)
library(ggsci)
library(knitcitations)
library(kableExtra)
library(Weatherfunctions)
library(xml2)
library(ggpmisc)
library(tidyr)
source("Q:/HUME/HUME/DokuUtilFunctions.R")
options("citation_format" = "pandoc")

```

# Introduction


```{r}
#| label: GetAncestorClasses
fn_source <- "Q:/HUME/HUME/Components/Soil/TSoilWaterModelR.pas"
fn_xml_docu <- "Q:/HUME/HUME/XML_Delphi_Docu/URootedSoil.xml"
ClassName <- "TSoilWaterModelR"


df.ancestors <- GetAncestorClasses (fn_xml_docu, ClassName) 

```


