---
title: "Plant Growth Model"
format: html
---

# Oilseed rape (OSR) plant growth model

## Crop height

Crop height was calculated with an exponential function based on growth stages and had an upper limit of 1.8 m (Eq. 1).

$$\text{CropHeight=min(1}\text{.8,}{{\text{p}}_{\text{H1}}}\text{*e}{{\text{ }\!\!~\!\!\text{ }}^{{{\text{p}}_{\text{H2}}}\text{*EC}}}\text{)}$$ (1)

## Dry matter production

Daily increase of crop dry matter (DMPlant, \[g m<sup>-2</sup>\] eqs. 2 and 3) was calculated from photosynthetic active radiation (PAR \[MJ m-2 d-1\]) absorbed by leaves (QLeaf \[MJ m<sup>-2</sup> d-1\], eq. 7) and pods (QPod \[MJ m-2 d-1\], eq. 8), potential light use efficiency (LUE \[g MJ-1\]) during vegetative (LUEveg) and generative (LUEgen) growth stages, a temperature dependent scaling factor for photosynthetic activity (fT, eq. 13) and a soil water deficit scaling factor (SWDF, eq. 9). N deficiencies were considered by an organ specific N deficit scaling factor (NNIi, section 2.2.2.7). During vegetative growth (EC \< 51), dry matter production is calculated as follows:

$$\frac{\text{dD}{{\text{M}}_{\text{Plant}}}}{\text{dt}}\text{= }\!\!~\!\!\text{ }{{\text{Q}}_{\text{Leaf}}}\text{*LU}{{\text{E}}_{\text{veg}}}\text{*}\left( \frac{\text{LAI*NN}{{\text{I}}_{\text{Leaf}}}\text{+SAI*NN}{{\text{I}}_{\text{Stem}}}}{\text{LAI+SAI}} \right)\text{*fT*SWDF}$$ (2) Dry matter production during generative growth (EC ? 51) is calculated according to the following equation:

$$\frac{\text{dD}{{\text{M}}_{\text{Plant}}}}{\text{dt}}\text{=((}{{\text{Q}}_{\text{Leaf}}}\text{*LU}{{\text{E}}_{\text{Gen}}}\text{*}\left( \frac{\text{LAI*NN}{{\text{I}}_{\text{Leaf}}}\text{+SAI*NN}{{\text{I}}_{\text{Stem}}}}{\text{LAI+SAI}} \right)\text{)+(}{{\text{Q}}_{\text{Pod}}}\text{*LU}{{\text{E}}_{\text{Gen}}}\text{*NN}{{\text{I}}_{\text{Gen}}}\text{))*fT*SWDF}$$ (3) where LAI is the leaf area index and SAI is the stem area index. This calculation of crop DM growth considers the net effect of photosynthesis and autotrophic respiration. However, during seed filling an increased respiration loss is assumed due to the conversion of carbohydrates to lipids in the growing seeds. This respiration loss is subtracted from the dry matter accumulation according to $$\text{Res}{{\text{p}}_{\text{loss}}}\text{=}\frac{\text{DMseed}}{\text{dt}}\text{*Oilconcentration*0}\text{.4}$$ (4) Absorbed PAR is reduced by canopy reflection. As in many crop growth models, the empirical extinction coefficient used to calculate light interception implicitly accounts for this effect. As long as LAI does not exceed LAIcrit of 1.5, light extinction coefficient of leaves (kLeaf) varies between 0.8 and 0.9 and is described by a negative linear-plateau function of LAI (eq. 6). This assumption is based on experimental data showing that kLeaf decreases with increasing LAI (Data set 2). To calculate the absorbed PAR by the crop, the light extinction coefficient of pods (kPod) and the pod area index (PAI) have to be considered. Furthermore, only a fraction (fTr) of PAR is transmitted to the leaves while the rest is reflected or absorbed by flowers and pods. Canopy architecture was simplified by assuming that flower and pod layers are located above the leaves. We assumed that at the onset of flowering, flower layer starts to absorb and reflect PAR (eq. 5). The proportion of absorbed and reflected PAR increases linearly with growth stage, until 30% of incoming PAR is absorbed and reflected by the flower layer at full flower. From full flower until end of flowering, the proportion of absorbed and reflected PAR decreases linearly.

$${{\text{f}}_{\text{Tr}}}\text{=}\left\{ \begin{array}{*{35}{l}}
   \text{1} & \text{EC60}  \\
   \text{1+}\frac{\text{0}\text{.7-1}}{\text{65-60}}\text{*(EC-60)} & \text{60}\le \text{EC}\le \text{65}  \\
   \text{0}\text{.7+}\frac{\text{1-0}\text{.7}}{\text{70-65}}\text{*(EC-65)} & \text{65EC}\le \text{70}  \\
   \text{1} & \text{EC70}  \\
\end{array} \right.$$ (5)

$${{\text{k}}_{\text{Leaf}}}\text{=0}\text{.9-}\left( \text{0}\text{.8-0}\text{.9} \right)\text{*}\frac{\text{LAI}}{\text{LA}{{\text{I}}_{\text{crit}}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ LAILA}{{\text{I}}_{\text{crit}}}$    (6)
${{\text{Q}}_{\text{Leaf}}}\text{=}\left\{ \begin{array}{*{35}{l}}
   \text{PAR*}\left( \text{1-}{{\text{e}}^{\text{-}{{\text{k}}_{\text{Leaf}}}\text{*LAI}}} \right)\text{*}{{\text{f}}_{\text{Tr}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ EC}\le \text{51}  \\
   \text{PAR- }\!\!~\!\!\text{ }{{\text{Q}}_{\text{Pod}}}\text{*}\left( \text{1-}{{\text{e}}^{\text{-}{{\text{k}}_{\text{Leaf}}}\text{*LAI}}} \right)\text{*}{{\text{f}}_{\text{Tr}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ EC51 }\!\!~\!\!\text{  }\!\!~\!\!\text{ }  \\
\end{array} \right.$$ (7)

$${{\text{Q}}_{\text{Pod}}}\text{=PAR*}\left( \text{1-}{{\text{e}}^{\text{-}{{\text{k}}_{\text{Pod}}}\text{*PAI}}} \right)$$ (8)

The soil water deficit factor is defined as the ratio between actual and potential transpiration (Tact/Tpot) and a parameter describing a non-linear response to drought stress (pfW), as proposed by Ferreyra et al. (2003):

$$\text{SWDF=1-(1-}\frac{{{\text{T}}_{\text{act}}}}{{{\text{T}}_{\text{pot}}}}{{\text{)}}^{\text{pfW}}}$$ (9)

The temperature function of photosynthetic activity (eq. 10) is described by an optimum function with four cardinal temperatures, as follows (Marshall and Squire 1996, Porter and Gawith 1999):

$$\text{fT=}\left\{ \begin{array}{*{35}{l}}
   \text{0, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ }{{\text{T}}_{\text{mean}}}\text{}{{\text{T}}_{\text{1}}}  \\
   \frac{{{\text{T}}_{\text{mean}}}\text{-}{{\text{T}}_{\text{1}}}}{{{\text{T}}_{\text{2}}}\text{-}{{\text{T}}_{\text{1}}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ }{{\text{T}}_{\text{1}}}\text{}\le {{\text{T}}_{\text{2}}}  \\
   \begin{array}{*{35}{l}}
   \text{1, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ }{{\text{T}}_{\text{2}}}\text{}{{\text{T}}_{\text{mean}}}\le {{\text{T}}_{\text{3}}}  \\
   \begin{array}{*{35}{l}}
   \frac{{{\text{T}}_{\text{4}}}\text{-}{{\text{T}}_{\text{mean}}}}{{{\text{T}}_{\text{4}}}\text{-}{{\text{T}}_{\text{3}}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ }{{\text{T}}_{\text{3}}}\text{}{{\text{T}}_{\text{mean}}}\le {{\text{T}}_{\text{4}}}  \\
   \text{0, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ }{{\text{T}}_{\text{mean}}}\text{}{{\text{T}}_{\text{4}}}  \\
\end{array}  \\
\end{array}  \\
\end{array} \right.$$ (10)

## Dry matter partitioning

Total dry matter growth is split between growth of root dry matter (DMRoot \[g m^-2^\], eq. 12) and shoot dry matter (DMShoot \[g m^-2^\], eq. 13). Before stem elongation, root dry matter growth depends on the temperature sum from emergence (Fehler! Verweisquelle konnte nicht gefunden werden.). The ratio dDMRoot/dDMPlant (fRoot, eq. 11) is described by an exponential function of the temperature sum after emergence (TempSumEmerge) with a base temperature of 3°C. From the beginning of stem elongation, fRoot decreased linearly to a minimum of 0.05 within 100°Cd. After flowering, it was assumed that 5% of total dry matter increase was allocated to the roots (Barraclough 1989).

$${{\text{f}}_{\text{Root}}}\text{=}\left\{ \begin{array}{*{35}{l}}
   \text{roo}{{\text{t}}_{\text{i}}}\text{*(TempSu}{{\text{m}}_{\text{Emerge}}}{{\text{)}}^{\text{2}}}\text{+roo}{{\text{t}}_{\text{s}}}\text{*TempSu}{{\text{m}}_{\text{Emerge}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ EC}\le \text{30}  \\
   \frac{\text{0}\text{.05-roo}{{\text{t}}_{\text{EC30}}}}{\text{100}}\text{*TempSum+roo}{{\text{t}}_{\text{EC30}}}\text{, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ 30EC}\le \text{69}  \\
   \text{0}\text{.05, }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{  }\!\!~\!\!\text{ EC69}  \\
\end{array} \right.$$ (11)

$$\begin{matrix}
   \frac{\text{dDMRoot}}{\text{dt}}\text{=fRoot*}\frac{\text{dDMPlant}}{\text{dt}}  \\
\end{matrix}$$ (12)

$$\frac{\text{dDMShoot}}{\text{dt}}\text{=}\frac{\text{dDMPlant}}{\text{dt}}\text{-}\frac{\text{dDMRoot}}{\text{dt}}$$ (13)
