Name;Value;Unit;Comment;""
RDGS1;3;"";Root depth growth rate,initial;""
RDGTH;275;"";Rooting depth growth threshold dd;""
RLIGP;10;"";Root lignin concentration  %;""
RLWR;20000;"";Root length/weight ratio ;""
RSEN;0.008;"";Root senescence fraction;""
RTREF;0.4;"";Root respiration fraction      [-];""
SHF;1;"";Soil hospitality factor      [-];""
STDDAY;20;"";Standard day temperature ;""
