var tipuesearch = {"pages": [
     {"title": "UAbstractPlant", "text": " This unit defines the abstract base class for plant submodels and related soil submodels. It includes properties and methods for managing plant growth, soil interactions, and environmental parameters. &lt;author&gt;HUME Development Team&lt;/author&gt;   ", "tags": "", "url": "UAbstractPlant.html"},
     {"title": "UAbstractPlant.TAbstractPlant", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html"},
     {"title": "UAbstractPlant.TAbstractPlant.C_Residues", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#C_Residues"},
     {"title": "UAbstractPlant.TAbstractPlant.DMFineRoot", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#DMFineRoot"},
     {"title": "UAbstractPlant.TAbstractPlant.DMtotal", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#DMtotal"},
     {"title": "UAbstractPlant.TAbstractPlant.DoHarvest", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#DoHarvest"},
     {"title": "UAbstractPlant.TAbstractPlant.fDMprodModel", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fDMprodModel"},
     {"title": "UAbstractPlant.TAbstractPlant.fEvapModel", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fEvapModel"},
     {"title": "UAbstractPlant.TAbstractPlant.fNextCrop", "text": " This property holds a reference to the next crop in the rotation.     @returns(next crop in the rotation)  NextCrop next crop to set NextCrop next crop to set", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fNextCrop"},
     {"title": "UAbstractPlant.TAbstractPlant.fRotationlength", "text": " This property defines the length of the crop rotation in years.     @returns(rotation length in years)  RotationLength rotation length in years RotationLength rotation length in years", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fRotationlength"},
     {"title": "UAbstractPlant.TAbstractPlant.fSetNewDates", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fSetNewDates"},
     {"title": "UAbstractPlant.TAbstractPlant.fSoilLayerMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fSoilLayerMod"},
     {"title": "UAbstractPlant.TAbstractPlant.fSoilMinMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fSoilMinMod"},
     {"title": "UAbstractPlant.TAbstractPlant.fSoilNitrogenMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fSoilNitrogenMod"},
     {"title": "UAbstractPlant.TAbstractPlant.fwithRoots", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#fwithRoots"},
     {"title": "UAbstractPlant.TAbstractPlant.HarvestDate", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#HarvestDate"},
     {"title": "UAbstractPlant.TAbstractPlant.Harvested", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Harvested"},
     {"title": "UAbstractPlant.TAbstractPlant.N_Residues", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#N_Residues"},
     {"title": "UAbstractPlant.TAbstractPlant.OptWithRoots", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#OptWithRoots"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_ExtCoeffPAR", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_ExtCoeffPAR"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_Psi2", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_Psi2"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_rc0", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_rc0"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_Weff", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_Weff"},
     {"title": "UAbstractPlant.TAbstractPlant.pWLD_arr", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#pWLD_arr"},
     {"title": "UAbstractPlant.TAbstractPlant.SowingDate", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SowingDate"},
     {"title": "UAbstractPlant.TAbstractPlant.GetCropHeight", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetCropHeight"},
     {"title": "UAbstractPlant.TAbstractPlant.getDM_c", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getDM_c"},
     {"title": "UAbstractPlant.TAbstractPlant.getExtCoeffGlobRad", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getExtCoeffGlobRad"},
     {"title": "UAbstractPlant.TAbstractPlant.getExtCoeffPAR", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getExtCoeffPAR"},
     {"title": "UAbstractPlant.TAbstractPlant.GetLAI", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetLAI"},
     {"title": "UAbstractPlant.TAbstractPlant.GetNUptakeRate", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetNUptakeRate"},
     {"title": "UAbstractPlant.TAbstractPlant.getPsi2", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getPsi2"},
     {"title": "UAbstractPlant.TAbstractPlant.getrc0", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getrc0"},
     {"title": "UAbstractPlant.TAbstractPlant.GetSumRootLength", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetSumRootLength"},
     {"title": "UAbstractPlant.TAbstractPlant.GetSumRootLength_eff", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetSumRootLength_eff"},
     {"title": "UAbstractPlant.TAbstractPlant.getWeff", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#getWeff"},
     {"title": "UAbstractPlant.TAbstractPlant.GetWLD", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#GetWLD-Integer-"},
     {"title": "UAbstractPlant.TAbstractPlant.CalcRates", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#CalcRates"},
     {"title": "UAbstractPlant.TAbstractPlant.CreateAll", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#CreateAll"},
     {"title": "UAbstractPlant.TAbstractPlant.Init", "text": " This method sets the initial conditions for the plant model harvest status, and residue states. It also ensures that the harvest date is set correctly relative to the sowing date.   GlobMod global model instance GlobMod global model instance ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Init-Tmod-"},
     {"title": "UAbstractPlant.TAbstractPlant.Integrate", "text": " This method checks if the harvest date has been reached or if harvesting is triggered. If so, it sets the harvested flag, adds residues to the soil model, and prepares the next crop for planting. It also resets state variables and updates sowing and harvest dates based on the rotation lengt furthermore it moves pointer of coupled submodels to the next crop in the rotation.    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Integrate"},
     {"title": "UAbstractPlant.TAbstractPlant.SetSowingDate", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetSowingDate-real-"},
     {"title": "UAbstractPlant.TAbstractPlant.SetCropHeight", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetCropHeight-THumeNumEntity-"},
     {"title": "UAbstractPlant.TAbstractPlant.SetDMprodModel", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetDMprodModel-TPlantRelatedSubMod-"},
     {"title": "UAbstractPlant.TAbstractPlant.setDM_c", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#setDM_c-real-"},
     {"title": "UAbstractPlant.TAbstractPlant.SetLai", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetLai-THumeNumEntity-"},
     {"title": "UAbstractPlant.TAbstractPlant.setNextCrop", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#setNextCrop-TAbstractplant-"},
     {"title": "UAbstractPlant.TAbstractPlant.SetNUptakeRate", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetNUptakeRate-THumeNumEntity-"},
     {"title": "UAbstractPlant.TAbstractPlant.setSoilNitrogenMod", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#setSoilNitrogenMod-TPlantRelatedSubmod-"},
     {"title": "UAbstractPlant.TAbstractPlant.SetWLD", "text": "    ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetWLD-Integer-THumeNumEntity-"},
     {"title": "UAbstractPlant.TAbstractPlant.DMprodModel", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#DMprodModel"},
     {"title": "UAbstractPlant.TAbstractPlant.EvapModel", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#EvapModel"},
     {"title": "UAbstractPlant.TAbstractPlant.ExtCoeffGlobRad", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#ExtCoeffGlobRad"},
     {"title": "UAbstractPlant.TAbstractPlant.ExtCoeffPAR", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#ExtCoeffPAR"},
     {"title": "UAbstractPlant.TAbstractPlant.NextCrop", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#NextCrop"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_HarvestDate", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_HarvestDate"},
     {"title": "UAbstractPlant.TAbstractPlant.Par_SowingDate", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Par_SowingDate"},
     {"title": "UAbstractPlant.TAbstractPlant.Psi2", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Psi2"},
     {"title": "UAbstractPlant.TAbstractPlant.p_CropHeight", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_CropHeight"},
     {"title": "UAbstractPlant.TAbstractPlant.p_LAI", "text": " This property returns the leaf area index of the plant.   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_LAI"},
     {"title": "UAbstractPlant.TAbstractPlant.p_NUptakeRate", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_NUptakeRate"},
     {"title": "UAbstractPlant.TAbstractPlant.p_SumRootLength", "text": " This property returns the total root length of the plant.   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_SumRootLength"},
     {"title": "UAbstractPlant.TAbstractPlant.p_SumRootLength_eff", "text": " This property returns the effective root length of the plant. The effective root length is the root length that is actively taking up water and nutrients.   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_SumRootLength_eff"},
     {"title": "UAbstractPlant.TAbstractPlant.p_TotalDryMatterGR", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_TotalDryMatterGR"},
     {"title": "UAbstractPlant.TAbstractPlant.p_WLD", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#p_WLD"},
     {"title": "UAbstractPlant.TAbstractPlant.rc0", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#rc0"},
     {"title": "UAbstractPlant.TAbstractPlant.Rotationlength", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Rotationlength"},
     {"title": "UAbstractPlant.TAbstractPlant.SetNewDates", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SetNewDates"},
     {"title": "UAbstractPlant.TAbstractPlant.SoilLayerMod", "text": " This property allows linking a soil layer submodel to the plant model.&lt;/remarks   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SoilLayerMod"},
     {"title": "UAbstractPlant.TAbstractPlant.SoilMinMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SoilMinMod"},
     {"title": "UAbstractPlant.TAbstractPlant.SoilNitrogenMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#SoilNitrogenMod"},
     {"title": "UAbstractPlant.TAbstractPlant.St_C_Residues", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#St_C_Residues"},
     {"title": "UAbstractPlant.TAbstractPlant.St_DMFineRoot", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#St_DMFineRoot"},
     {"title": "UAbstractPlant.TAbstractPlant.St_DMtotal", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#St_DMtotal"},
     {"title": "UAbstractPlant.TAbstractPlant.St_N_Residues", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#St_N_Residues"},
     {"title": "UAbstractPlant.TAbstractPlant.Weff", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#Weff"},
     {"title": "UAbstractPlant.TAbstractPlant.withRoots", "text": "   ", "tags": "", "url": "UAbstractPlant.TAbstractPlant.html#withRoots"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.fFirstPlantMod", "text": "   ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#fFirstPlantMod"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.fPlantModel", "text": "   ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#fPlantModel"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.GetIsPlantModelset", "text": "     boolean indicating if a plant model is set", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#GetIsPlantModelset"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.Init", "text": "    ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#Init-Tmod-"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.SetPlantModel", "text": "     This method sets the plant model and initializes the first plant model if not already set.  NewPlantModel new plant model to set NewPlantModel new plant model to set ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#SetPlantModel-TAbstractPlant-"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.IsPlantModelSet", "text": "   ", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#IsPlantModelSet"},
     {"title": "UAbstractPlant.TPlantRelatedSubMod.PlantModel", "text": " This property allows access to the current plant model instance. @returns(current plant model)     This property allows setting the plant model for the submodel.  PlantModel new plant model to set PlantModel new plant model to set", "tags": "", "url": "UAbstractPlant.TPlantRelatedSubMod.html#PlantModel"},
     {"title": "UAbstractPlant.max_comp", "text": "   ", "tags": "", "url": "UAbstractPlant.html#max_comp"},
     {"title": "UAbstractPlant.max_rootedcomp", "text": "   ", "tags": "", "url": "UAbstractPlant.html#max_rootedcomp"},
     {"title": "UAbstractPlant.real", "text": "   ", "tags": "", "url": "UAbstractPlant.html#real"},
     {"title": "UAbstractPlant.TSource", "text": "    fromParameter    fromPlantModel   ", "tags": "", "url": "UAbstractPlant.html#TSource"},
     {"title": "UGrowthCurvePlant", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.html"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant", "text": "    This class extends TAbstractPlant and provides methods for calculating growth rates, integrating state variables, and handling temperature effects on plant growth. It also supports soil nitrogen uptake if enabled.   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CurveOptions", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CurveOptions"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CurveSwitches", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CurveSwitches"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CurveTypes", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CurveTypes"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.C_cont_Res", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#C_cont_Res"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.fEmergence", "text": " This boolean flag is set to true when the plant has emerged from the soil   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#fEmergence"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.fWithNUptake", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#fWithNUptake"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.GrowthRates", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#GrowthRates"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Harvestindex", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Harvestindex"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.IntPolVals", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#IntPolVals"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.N_Harvestindex", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#N_Harvestindex"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Parameters", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Parameters"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.plantIsGrowing", "text": " This boolean flag is set to true when the plant is actively growing, false otherwise.   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#plantIsGrowing"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.SoilNUptakeGrowthRate", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#SoilNUptakeGrowthRate"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.StateVars", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#StateVars"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.SumSoilNUptakeGrowth", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#SumSoilNUptakeGrowth"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Temp", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Temp"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.TempSumEmerge", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#TempSumEmerge"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.TSum", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#TSum"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.TSum_DM", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#TSum_DM"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CalcGrowthRate", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CalcGrowthRate-real-real-real-real-real-real-real-TGrowth-TStateVars-"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.GetCropHeight", "text": "  This method retrieves the current crop height from the state variables.    Crop Height as a THumeNumEntity", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#GetCropHeight"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.GetLAI", "text": "  This method retrieves the current Leaf Area Index from the state variables.    Leaf Area Index as a THumeNumEntity", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#GetLAI"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.GetNUptakeRate", "text": "  This method retrieves the current nitrogen uptake rate from the growth rates.    Nitrogen uptake rate as a THumeNumEntity", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#GetNUptakeRate"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CalcRates", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CalcRates"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.CreateAll", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#CreateAll"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Init", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Init-Tmod-"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Integrate", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Integrate"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Ex_Temp", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Ex_Temp"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Par_LAImax", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Par_LAImax"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.Par_TempsumEmerge", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#Par_TempsumEmerge"},
     {"title": "UGrowthCurvePlant.TGrowthCurvePlant.withNUptake", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.TGrowthCurvePlant.html#withNUptake"},
     {"title": "UGrowthCurvePlant.MaxVals", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.html#MaxVals"},
     {"title": "UGrowthCurvePlant.Parnames", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.html#Parnames"},
     {"title": "UGrowthCurvePlant.ParUnits", "text": " be aware that the the units can not defined independently from the state variables   ", "tags": "", "url": "UGrowthCurvePlant.html#ParUnits"},
     {"title": "UGrowthCurvePlant.Statenames", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.html#Statenames"},
     {"title": "UGrowthCurvePlant.StateUnits", "text": "   ", "tags": "", "url": "UGrowthCurvePlant.html#StateUnits"},
     {"title": "UGrowthCurvePlant.Register", "text": "    ", "tags": "", "url": "UGrowthCurvePlant.html#Register"},
     {"title": "UGrowthCurvePlant.TGrowth", "text": "    Logistisch    LogIntBased    Monomolekular    Gompertz    Richards    Linear    expolinear    LogIntDecay    Log_Decay    IntPol   ", "tags": "", "url": "UGrowthCurvePlant.html#TGrowth"},
     {"title": "UGrowthCurvePlant.TParameters", "text": " / be aware that th meaning of the parameters depends on the growth curve type    BaseTemp    rgr    gr    Capacity    Richards_f    IniValue   ", "tags": "", "url": "UGrowthCurvePlant.html#TParameters"},
     {"title": "UGrowthCurvePlant.TStateVars", "text": "    LAI    DM    CropHeight    ShootN   ", "tags": "", "url": "UGrowthCurvePlant.html#TStateVars"},
     {"title": "UGrowthCurvePlantRoots", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.html"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html"},
     {"title": "UGrowthCurvePlantRoots.K_a", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#K_a"},
     {"title": "UGrowthCurvePlantRoots.k_Wl", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#k_Wl"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.ActiveDuration", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#ActiveDuration"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.depthgrowthchoice", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#depthgrowthchoice"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.depthgrowthOptStr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#depthgrowthOptStr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.EffWld_arr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#EffWld_arr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.effWL_arr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#effWL_arr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.k_z", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#k_z"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.n_age_cl", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#n_age_cl"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.N_Rootcomp", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#N_Rootcomp"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Opt_RootAgeing", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Opt_RootAgeing"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Root_Matrix", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Root_Matrix"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.SRL", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#SRL"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.SRL_eff", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#SRL_eff"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Tiefe", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Tiefe"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Wld_arr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Wld_arr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.WL_0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#WL_0"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.WL_arr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#WL_arr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.WL_max", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#WL_max"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.zr_0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#zr_0"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.zr_max", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#zr_max"},
     {"title": "UGrowthCurvePlantRoots.zr", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#zr"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.GetSumRootLength", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#GetSumRootLength"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.GetSumRootLength_eff", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#GetSumRootLength_eff"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.GetWLD", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#GetWLD-Integer-"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.WLD_z_t_f", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#WLD_z_t_f-real-real-real-real-real-real-real-"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.CalcRates", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#CalcRates"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.CreateAll", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#CreateAll"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Init", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Init-Tmod-"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_ActiveDuration", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_ActiveDuration"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_kWL", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_kWL"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_kz", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_kz"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_Wl0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_Wl0"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_Wlmax", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_Wlmax"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_zr0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_zr0"},
     {"title": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.Par_zrmax", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.TGrowthCurvePlantRoots.html#Par_zrmax"},
     {"title": "UGrowthCurvePlantRoots.MaxAgeCl", "text": "   ", "tags": "", "url": "UGrowthCurvePlantRoots.html#MaxAgeCl"},
     {"title": "UGrowthCurvePlantRoots.Register", "text": "    ", "tags": "", "url": "UGrowthCurvePlantRoots.html#Register"},
     {"title": "UGrowthCurvePlantRoots.TRootDepthgrowth", "text": "    linear    monomolecular   ", "tags": "", "url": "UGrowthCurvePlantRoots.html#TRootDepthgrowth"},
     {"title": "UGrowthCurvePlantsRootDM", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.html"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.FFineroot", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#FFineroot"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.fFineRoot0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#fFineRoot0"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.FFineRootDec", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#FFineRootDec"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.CalcRates", "text": "    ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#CalcRates"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.createAll", "text": "    ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#createAll"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.Par_FFineRoot0", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#Par_FFineRoot0"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.Par_FFineRootDec", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#Par_FFineRootDec"},
     {"title": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.Var_FFineRoot", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.TGrowthCurvePlantRootDM.html#Var_FFineRoot"},
     {"title": "UGrowthCurvePlantsRootDM.Register", "text": "    ", "tags": "", "url": "UGrowthCurvePlantsRootDM.html#Register"},
     {"title": "UGrowthCurvePlantsRootDM.real", "text": "   ", "tags": "", "url": "UGrowthCurvePlantsRootDM.html#real"}
]};
